In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
file_path = '/content/drive/MyDrive/Major_Project/Codebase/training/labeled_training.csv'

In [24]:
import pandas as pd
train1 = pd.read_csv(file_path)
df = pd.DataFrame(train1)
df

        id                                               text   source  label
0        1  at 50 votes i will close this survey and take ...  twitter      0
1        2  21st birthday and nearly 4 months pregnant, no...  twitter      1
2        3  @_DudeThePie // I'd be killed. He's literally ...  twitter      0
3        4  This year I'm gonna become a mum and turn 20, ...  twitter      1
4        5  Don't mind me. Just freaking out because Mary-...  twitter      0
...    ...                                                ...      ...    ...
8795  8796  Happy Birthday Brandon James. Hope you have a ...  twitter      0
8796  8797  @JonBaker At age 50, I remember cheering "bana...  twitter      0
8797  8798  Them Springfield mall pictures.. lol. #va #bda...  twitter      1
8798  8799  @316Andres88 when we turn 18 were going idgaf ...  twitter      0
8799  8800  @JanielftJano @Janielkawaii Fanmeosmwhskd me w...  twitter      0

[8800 rows x 4 columns]

In [25]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text_with_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Remove English stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

def preprocess_text_without_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [26]:
df['cleaned_text_1'] = df['text'].apply(preprocess_text_with_stop_words)
df['cleaned_text_2'] = df['text'].apply(preprocess_text_without_stop_words)
df

,id,text,source,label,cleaned_text_1,cleaned_text_2
0,1,at 50 votes i will close this survey and take ...,twitter,0,50 votes close survey take new photos,at 50 votes i will close this survey and take ...
1,2,"21st birthday and nearly 4 months pregnant, no...",twitter,1,21st birthday nearly 4 months pregnant,21st birthday and nearly 4 months pregnant no
2,3,@_DudeThePie // I'd be killed. He's literally ...,twitter,0,killed literally 10th picture https,i be killed he literally my 10th picture https
3,4,"This year I'm gonna become a mum and turn 20, ...",twitter,1,year gon na become mum turn 20 waaaaah,this year i gon na become a mum and turn 20 wa...
4,5,Don't mind me. Just freaking out because Mary-...,twitter,0,mind freaking ashley olsen turned https,do mind me just freaking out because and ashle...
...,...,...,...,...,...,...
8795,8796,Happy Birthday Brandon James. Hope you have a ...,twitter,0,happy birthday brandon james hope fabulous 23r...,happy birthday brandon james hope you have a f...
8796,8797,"@JonBaker At age 50, I remember cheering ""bana...",twitter,0,age 50 remember cheering bananas hollaback girl,at age 50 i remember cheering bananas before h...
8797,8798,Them Springfield mall pictures.. lol. #va #bda...,twitter,1,springfield mall pictures lol va bday 17yearsy...,them springfield mall pictures lol va bday 17y...
8798,8799,@316Andres88 when we turn 18 were going idgaf ...,twitter,0,turn 18 going idgaf nigga road trip https,when we turn 18 were going idgaf where its at ...
8799,8800,@JanielftJano @Janielkawaii Fanmeosmwhskd me w...,twitter,0,fanmeosmwhskd turn 18 get matching tattoos,fanmeosmwhskd me when i turn 18 so we can get ...

In [28]:
df.to_csv("/content/drive/MyDrive/Major_Project/Codebase/training/labeled_preprocessed_training.csv", index=False)