In [ ]:
rom google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = '/content/drive/MyDrive/Major_Project/Codebase/training/unlabeled_training_reddit.csv'

In [ ]:
import pandas as pd
train2 = pd.read_csv(file_path)
df = pd.DataFrame(train2)
df

,id,subreddit,author,title,text,timestamp
0,bz796p,AskDocs,Scrambles99,Intestinal Issues,I am a young man age 19. Before this illness I...,2019-06-11 03:10:16
1,m7mwkd,AskDocs,KingCeryn,"Neck muscle flexing, possibly Omohyoid, anytim...","29 years old, male, 130 pounds, I have a doc...",2021-03-18 09:12:34
2,2mh45q,AskDocs,Mordor_or_bust,29/F Brown urine &amp; flu-like symptoms,About 5 or 6 months ago I became sick with wha...,2014-11-16 16:45:48
3,2fq5mh,AskDocs,yeast-1,Question about anti-fungal creams or lotions,"Age:31. Male. 6'0"", 205#, White, PmHX: HTN (tr...",2014-09-07 16:05:07
4,8ihond,AskDocs,Derek800,Elevated Lipase and Amylase,"Hello, I've asked this question on here a lit...",2018-05-10 19:47:09
...,...,...,...,...,...,...
99995,gewohl,AskDocs,BlueTipi,Why can't I eat quietly?,People often tell me that I'm a very noisy eat...,2020-05-07 00:59:22
99996,blnbah,AskDocs,plywooddrywall,Red/Purple blotches on pubic area won't go away,I think it all started when I shaved my pubic ...,2019-05-07 06:29:16
99997,ndql1u,AskDocs,1g0tquestions,Are high testosterone and estrogen a good sign?,Some of the symptoms which I had been experien...,2021-05-16 15:21:11
99998,tearhc,AskDocs,Hannah2482,Is a 32F bra size + back pain enough for a bre...,Hi all. So I’m 18F 5’7 142 pounds and I have s...,2022-03-14 23:23:07
99999,qukw0e,AskDocs,TheBlank_One,"Liver lesions, Mets or nothing?","Hi, 28 y/o male, non smoker, not heavy drinker...",2021-11-15 16:56:59

In [ ]:
df = df.drop(columns=["subreddit", "timestamp"])
df

,id,author,title,text
0,bz796p,Scrambles99,Intestinal Issues,I am a young man age 19. Before this illness I...
1,m7mwkd,KingCeryn,"Neck muscle flexing, possibly Omohyoid, anytim...","29 years old, male, 130 pounds, I have a doc..."
2,2mh45q,Mordor_or_bust,29/F Brown urine &amp; flu-like symptoms,About 5 or 6 months ago I became sick with wha...
3,2fq5mh,yeast-1,Question about anti-fungal creams or lotions,"Age:31. Male. 6'0"", 205#, White, PmHX: HTN (tr..."
4,8ihond,Derek800,Elevated Lipase and Amylase,"Hello, I've asked this question on here a lit..."
...,...,...,...,...
99995,gewohl,BlueTipi,Why can't I eat quietly?,People often tell me that I'm a very noisy eat...
99996,blnbah,plywooddrywall,Red/Purple blotches on pubic area won't go away,I think it all started when I shaved my pubic ...
99997,ndql1u,1g0tquestions,Are high testosterone and estrogen a good sign?,Some of the symptoms which I had been experien...
99998,tearhc,Hannah2482,Is a 32F bra size + back pain enough for a bre...,Hi all. So I’m 18F 5’7 142 pounds and I have s...
99999,qukw0e,TheBlank_One,"Liver lesions, Mets or nothing?","Hi, 28 y/o male, non smoker, not heavy drinker..."

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text_with_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Remove English stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

def preprocess_text_without_stop_words(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Remove usernames
    text = re.sub(r'@(\w+)', '', text)

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z0-9]+$', word)]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df['cleaned_text_1'] = df['text'].apply(preprocess_text_with_stop_words)
df['cleaned_text_2'] = df['text'].apply(preprocess_text_without_stop_words)

In [ ]:
df

,id,author,title,text,cleaned_text_1,cleaned_text_2
0,bz796p,Scrambles99,Intestinal Issues,I am a young man age 19. Before this illness I...,young man age illness 197 lb 6 0 15 bodyfat mu...,i am a young man age before this illness i was...
1,m7mwkd,KingCeryn,"Neck muscle flexing, possibly Omohyoid, anytim...","29 years old, male, 130 pounds, I have a doc...",29 years old male 130 pounds doctors appointme...,29 years old male 130 pounds i have a doctors ...
2,2mh45q,Mordor_or_bust,29/F Brown urine &amp; flu-like symptoms,About 5 or 6 months ago I became sick with wha...,5 6 months ago became sick seemed like bad sto...,about 5 or 6 months ago i became sick with wha...
3,2fq5mh,yeast-1,Question about anti-fungal creams or lotions,"Age:31. Male. 6'0"", 205#, White, PmHX: HTN (tr...",male 6 0 205 white pmhx htn treated ace inhibi...,male 6 0 205 white pmhx htn treated with ace i...
4,8ihond,Derek800,Elevated Lipase and Amylase,"Hello, I've asked this question on here a lit...",hello asked question little back issue continu...,hello i asked this question on here a little w...
...,...,...,...,...,...,...
99995,gewohl,BlueTipi,Why can't I eat quietly?,People often tell me that I'm a very noisy eat...,people often tell noisy eater try chew slowly ...,people often tell me that i a very noisy eater...
99996,blnbah,plywooddrywall,Red/Purple blotches on pubic area won't go away,I think it all started when I shaved my pubic ...,think started shaved pubic hair short 5 years ...,i think it all started when i shaved my pubic ...
99997,ndql1u,1g0tquestions,Are high testosterone and estrogen a good sign?,Some of the symptoms which I had been experien...,symptoms experiencing fatigue lethargy brain f...,some of the symptoms which i had been experien...
99998,tearhc,Hannah2482,Is a 32F bra size + back pain enough for a bre...,Hi all. So I’m 18F 5’7 142 pounds and I have s...,hi 18f 5 7 142 pounds size breasts feel like p...,hi all so i m 18f 5 7 142 pounds and i have si...
99999,qukw0e,TheBlank_One,"Liver lesions, Mets or nothing?","Hi, 28 y/o male, non smoker, not heavy drinker...",hi 28 male non smoker heavy drinker 2018 diagn...,hi 28 male non smoker not heavy drinker in 201...

In [ ]:
df.to_csv("/content/drive/MyDrive/Major_Project/Codebase/training/unlabeled_preprocessed_training.csv", index=False)